import DBD-Oracle 0.45 from CPAN
git-cpan-module:   DBD-Oracle
git-cpan-version:  0.45
git-cpan-authorid: TIMB
git-cpan-file:     authors/id/T/TI/TIMB/DBD/Oracle/DBD-Oracle-0.45.tar.gz

diff --git a/Makefile.PL b/Makefile.PL
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -1,5 +1,4 @@
-#!/usr/local/bin/perl -sw
-# $Id: Makefile.PL,v 1.52 1997/01/14 21:48:19 timbo Exp $
+# $Id: Makefile.PL,v 1.53 1997/06/14 17:42:12 timbo Exp $
 
 BEGIN { require 5.003 }	# 5.003 fixes very important bugs
 
@@ -15,7 +14,11 @@ require FileHandle unless defined(&FileHandle::new);
 # For those not using Dynamic loading this means building a
 # new static perl in the DBI directory by saying 'make perl'
 # and then using _that_ perl to make this one.
-use DBI 0.71;
+use DBI 0.82;
+
+my $osname = $^O;
+my $osvers = $Config{osvers};
+$osvers =~ s/^\s*(\d+\.\d+).*/$1/;	# drop sub-sub-version: 2.5.1 -> 2.5
 
 my %opts = (
     NAME => 'DBD::Oracle',
@@ -23,17 +26,20 @@ my %opts = (
     dist  => { DIST_DEFAULT=> 'clean distcheck disttest ci tardist',
                 PREOP => '$(MAKE) -f Makefile.old distdir' },
 );
-my(@MK, %MK, $MK);	# parsed macros from Oracle proc.mk file
+my(@MK, %MK, $MK);	# parsed macros from Oracle's makefiles
 
 # Options (rarely needed)
 $::opt_m = '';		# path to proc.mk or oracle.mk file to read
+$::opt_p = '';		# prefer oracle.mk over proc
 $::opt_g = '';		# enable debugging (s/-O/-g/g)
 $::opt_s = '';		# Find a symbol, Don't build a Makefile
-$::opt_v = 0;		# be verbose
+$::opt_v = 0;		# be more verbose
+$::opt_old = 0;		# old style .mk file parsing
 
-GetOptions('v!', 'g!', 'm=s', 's=s') or die "Invalid arguments";
+GetOptions(qw(v! g! old! p! m=s s=s)) or die "Invalid arguments";
 
 $::opt_g &&= '-g';	# convert to actual string
+$Verbose = 1 if $::opt_v;
 
 # --- Introduction
 
@@ -45,99 +51,122 @@ print "\n Configuring DBD::Oracle ...\n
 
 # --- Where is Oracle installed...
 
-unless ($ENV{ORACLE_HOME}){
-    warn "\$ORACLE_HOME not defined. Searching for Oracle...\n";
-    foreach(qw(/usr/oracle /home/oracle /opt/oracle /home/oracle/home)){
-        $ENV{ORACLE_HOME}=$_,last
-	    if -d "$_/rdbms" or -d "$_/precomp" or -d "$_/ocommon";
-    }
-    die "Unable to determine ORACLE_HOME" unless $ENV{ORACLE_HOME};
-}
+die "ORACLE_HOME environment variable must be set.\n"
+	unless $ENV{ORACLE_HOME};
 my $OH = $ENV{ORACLE_HOME};
+die "ORACLE_HOME environment variable ($OH) not value.\n"
+	unless -d $OH;
+my $OCIDIR = "OCI73";	# For MSWin32. XXX what about 7.4 etc?
 
 print "Using Oracle in $OH\n";
 
 
-# --- What Oracle is installed...
+my @mkplaces = qw(
+    rdbms/demo/oracle.mk
+    proc/lib/proc.mk
+    precomp/demo/proc/proc.mk
+    proc16/lib/proc16.mk
+);
+# if -p then remove oracle.mk from search list, prefer Pro*C
+@mkplaces = grep { !m/oracle\.mk\b/ } @mkplaces if $::opt_p;
+unshift @mkplaces, $::opt_m  if $::opt_m;
+my($mkfile, $place);
+foreach $place (@mkplaces) {
+    $place = "$OH/$place" unless $place =~ m:^[./]:;
+    $mkfile = $place if -f $place;
+    last if $mkfile;
+}
+if (!$mkfile and "@mkplaces" !~ m/oracle\.mk/) {
+    warn "Unable to locate a Pro*C *.mk. Falling back to oracle.mk.\n";
+    $mkfile = "$OH/oracle.mk";
+    push @mkplaces, $mkfile; # just for error message below
+}
+die qq{
+    Unable to locate an oracle.mk or proc.mk file in your Oracle installation.
+    (Looked in @mkplaces)
 
-warn "\nWARNING: Oracle OCI (Pro*C) does not appear to be installed.\n"
-	."You should install Pro*C before you can build DBD::Oracle properly.\n\n"
-    unless (-f "$OH/lib/libocic.a"
-			and (-f "$OH/rdbms/demo/oratypes.h" or -f "$OH/rdbms/public/oratypes.h"))
-		or (-f "$OH/precomp/demo/proc/proc.mk");	# 7.3.x
-# XXX Todo: validate user has all the right Oracle stuff installed.
+    The oracle.mk file is part of the Oracle RDBMS product. The
+    proc.mk file is part of the Oracle Pro*C product.  You need to
+    build DBD::Oracle on a system which has one of these installed.
 
-# Using -m to specify oracle.mk might work but is NOT supported.
-my $procmk = $::opt_m || "$OH/proc/lib/proc.mk";
-$procmk = "$OH/precomp/demo/proc/proc.mk" unless -f $procmk; # 7.3.x
-$procmk = "$OH/proc16/lib/proc16.mk"      unless -f $procmk;
-die q{
-	Unable to locate proc.mk in your Oracle installation.
+    If your oracle.mk or proc.mk file is installed somewhere
+    non-standard you can specify where it is using the -m option:
+	    perl Makefile.PL -m /path/to/your.mk
 
-	proc.mk is part of the Oracle Pro*C product. You should build
-	DBD::Oracle on a system which has Oracle Pro*C installed.
+    See README.clients for more information and some alternatives.
 
-	If proc.mk is installed somewhere non-standard you can use
-		perl Makefile.PL -m /path/to/proc.mk
-	to specify where it is.
+} unless ($osname eq 'MSWin32') || ($mkfile && -f $mkfile);
 
-	See README.clients for more information and some alternatives.
+my(@mkfiles, $linkvia, $libhome, $linkwith, $linkwith_s, @linkwith_o, $OCIINCLUDE);
 
-} unless -f $procmk;
+if ($osname ne 'MSWin32') {
+    $linkvia  = fetch_oci_macros($mkfile);
+    $libhome  = expand_mkvars($MK{LIBHOME}, 0, 1, 0) || "$OH/lib";
+    $linkwith = expand_mkvars($linkvia,     0, 1, 0);
+    $linkwith =~ s/-Y P,/-YP,/g if $Config{'cc'} =~ /gcc/;
+    $linkwith =~ s:-R /:-R/:g if $osname eq 'solaris';
 
-my @mkfiles;
-my $linkwith = fetch_oci_macros();
-my $libhome  = expand_mkvars($MK{LIBHOME}, 0, 1, 0) || "$OH/lib";
-$linkwith    = expand_mkvars($linkwith,    0, 1, 0);
-$linkwith =~ s/-Y P,/-YP,/g if $Config{'cc'} =~ /gcc/;
-$linkwith =~ s:-R /:-R/:g if $Config{osname} eq 'solaris';
+    # get a cut down $linkwith to pass to MakeMaker liblist
+    $linkwith_s = expand_mkvars($linkwith, 1, 1, 0);
+    # convert "/full/path/libFOO.a" into "-L/full/path -lFOO"
+    $linkwith_s =~ s!([/\w.]+)/lib(\w+).a!-L$1 -l$2!g;
+    # extract object files, keep for use later
+    push @linkwith_o, $1 while $linkwith_s =~ s/(\S+\.[oa])\b//;
+    # also extract AIX .exp files since they confuse MakeMaker
+    push @linkwith_o, $1 while $linkwith_s =~ s/(-bI:\S+\.exp)\b//;
 
-# get a cut down $linkwith to pass to MakeMaker liblist
-my $linkwith_s = expand_mkvars($linkwith, 1, 1, 0);
-# convert "/full/path/libFOO.a" into "-L/full/path -lFOO"
-$linkwith_s =~ s!([/\w.]+)/lib(\w+).a!-L$1 -l$2!g;
-# extract object files, keep for use later
-my @linkwith_o;
-push @linkwith_o, $1 while $linkwith_s =~ s/(\S+\.[oa])\b//;
-# also extract AIX .exp files since they confuse MakeMaker
-push @linkwith_o, $1 while $linkwith_s =~ s/(-bI:\S+\.exp)\b//;
-
-if ($::opt_s) {
+    if ($::opt_s) {
 	warn "Searching for symbol '$::opt_s' in $OH ...\n";
 	my $dlext = $Config{dlext};
 	system(qq{	cd $OH; for i in lib/*.[ao] lib/*.$dlext */lib/*.[ao];
-				do echo "  searching \$i ..."; nm \$i | grep $::opt_s;
-				done
-			});
+	    do echo "  searching \$i ..."; nm \$i | grep $::opt_s;
+	    done
+	});
 	warn "Search done.\n";
 	exit;
-}
+    }
 
-if ($Config{osname} eq 'solaris' and $Config{osvers} >= 2.3
-		and $linkwith_s =~ /-lthread/) {
+    if ($osname eq 'solaris' and $osvers >= 2.3
+				     and $linkwith_s =~ /-lthread/) {
 	warn "Warning: Solaris 2.5 bug #1224467 may cause '_rmutex_unlock' error.\n";
 	warn "Deleting -lthread from link list as a possible workround.\n";
 	$linkwith_s =~ s/\s*-lthread\b/ /g;
+    }
+
+    $OCIINCLUDE = $MK{INCLUDE} || '';
+    $opts{LIBS} = [ "-L$libhome $linkwith_s" ];
+    $opts{dynamic_lib} = { OTHERLDFLAGS => "$::opt_g @linkwith_o \$(COMPOBJS)" };
+    $opts{OBJECT} = '$(O_FILES)';
+}
+else {	# MSWin32
+    # this assumes MSVC...
+    $OCIINCLUDE = "-I$OH/$OCIDIR/include";
+    $opts{LIBS} = [ "-L$OH/$OCIDIR/LIB/MSVC/OCIW32.LIB"];
+    $opts{dynamic_lib} = { OTHERLDFLAGS => " $OH/$OCIDIR/LIB/MSVC/OCIW32.LIB" };
+    $opts{OBJECT} = '$(O_FILES)';
+    $opts{SKIP} = ['processPL'];    # XXX caused problems with Nmake...
 }
 
-my $OCIINCLUDE = $MK{INCLUDE} || '';
-$opts{LIBS} = [ "-L$libhome $linkwith_s" ];
-# INSTALLARCHLIB included _after_ INSTALLSITEARCH for transition period
-$opts{INC}  = "$OCIINCLUDE -I$OH/rdbms/demo -I\$(INSTALLSITEARCH)/DBI -I\$(INSTALLARCHLIB)/DBI";
-$opts{dynamic_lib} = { OTHERLDFLAGS => "$::opt_g @linkwith_o \$(COMPOBJS)" };
-$opts{OBJECT} = '$(O_FILES)';
-
-
+$opts{INC}  = "$OCIINCLUDE -I$OH/rdbms/demo -I\$(INSTALLSITEARCH)/auto/DBI";
 
 # --- Handle special cases ---
 
 # HP-UX 9 cannot link a non-PIC object file into a shared library.
 # Since the # .a libs that Oracle supplies contain non-PIC object
 # files, we sadly have to build static on HP-UX 9 :(
-if ($Config{osname} eq 'hpux' and $Config{osvers} < 10) {
-    print "Warning: forced to build static not dynamic on $Config{osname} $Config{osvers}\n";
-    print "         See README and Makefile.PL for more information.\n";
+if ($osname eq 'hpux' and $osvers < 10) {
     $opts{LINKTYPE} = 'static';
+    print "Warning: Forced to build static not dynamic on $osname $osvers.\a\n";
+    print "** Note: DBD::Oracle will be built *into* a NEW perl binary. You MUST use that new perl.\n";
+    print "         See README and Makefile.PL for more information.\a\n";
+}
+if ($osname eq 'hpux' and $osvers >= 10) {
+	print "Warning: You may need to build using static linking. See the README file.\n\a";
+}
+
+if ($osname eq 'aix' and $osvers >= 4 and $Config{cc} ne 'xlc_r') {
+	print "Warning: You may need to rebuild perl using the xlc_r compiler.\a\n";
+	print "         You may also need do: ORACCENV='cc=xlc_r'; export ORACCENV\n";
 }
 
 $opts{DEFINE} = '-Wall -pedantic -Wno-comment -Wtraditional'
@@ -151,28 +180,23 @@ warn "WARNING: Your GNU C compiler is very old. Please upgrade.\n"
 # Set some private WriteMakefile options if this is 'me' :-)
 if ($ENV{LOGNAME} eq 'timbo' and $ENV{S_ARCH_SW}){  # a reasonable guess
     $Verbose = 1;
-    # $opts{INST_LIB}     = '$(INSTALLSITELIB)';
-    # $opts{INST_ARCHLIB} = '$(INSTALLSITEARCH)';
-	$opts{DEFINE} .= ' -Wcast-align -Wconversion -Wpointer-arith'
-	    . ' -Wbad-function-cast -Wcast-qual' if $Config{cc} eq 'gcc';
+    $opts{DEFINE} .= ' -Wcast-align -Wconversion -Wpointer-arith'
+	. ' -Wbad-function-cast -Wcast-qual' if $Config{cc} eq 'gcc';
 }
-$Verbose = 1 if $::opt_v;
 
 # log key platform information to help me help you quickly
 print "System: perl$] @Config{qw(myuname)}\n";
 print "Compiler: @Config{qw(cc optimize ccflags)}\n";
-print "Linker:   ". find_bin('ld') ."\n";
+print "Linker:   ". (find_bin('ld')||"not found") ."\n";
 print "Oracle proc.mk would have used these values but we override them:\n";
-print "  CC:       $MK{CC}\n"		if $MK{CC};
-print "  CFLAGS:   $MK{CFLAGS}\n"	if $MK{CFLAGS};
-print "  LDFLAGS:  $MK{LDFLAGS}\n"	if $MK{LDFLAGS};
-print "  LDSTRING: $MK{LDSTRING}\n"	if $MK{LDSTRING};
-print "Linking with @linkwith_o $linkwith_s\n";
-
-# Assorted hints - these should be move to a hints subdirectory
-#print "See README notes about SPARCompiler on Solaris\n"
-#    if -d "/opt/SUNWspro/bin" and $Config{osname} eq 'solaris';
-
+print "  CC:       $MK{CC}\n"	if $MK{CC};
+print "  CFLAGS:   $MK{CFLAGS}\n"                  if $MK{CFLAGS};
+print "           [".mkvar('CFLAGS',1,0,0).  "]\n" if $MK{CFLAGS};
+print "  LDFLAGS:  $MK{LDFLAGS}\n"                 if $MK{LDFLAGS};
+print "           [".mkvar('LDFLAGS',1,0,0). "]\n" if $MK{LDFLAGS};
+print "  LDSTRING: $MK{LDSTRING}\n"                if $MK{LDSTRING};
+print "           [".mkvar('LDSTRING',1,0,0)."]\n" if $MK{LDSTRING};
+print "\nLinking with @linkwith_o $linkwith_s [from $linkvia]\n";
 print "\n";
 
 WriteMakefile(%opts);
@@ -247,24 +271,31 @@ ORACLE_HOME = '.$ENV{ORACLE_HOME}.'
 }
 
 
-sub fetch_oci_macros {
+sub del_crtobj {
+    # E.g. for changing the COMPOBJS line
+    # old: $(COMPOBJ)/crti.o $(COMPOBJ)/crt1.o $(COMPOBJ)/__fstd.o
+    # new: $(COMPOBJ)/__fstd.o
+    s:\$\S+?/crt[1in]\.o\b::g;
+}
 
-    # Read $procmk makefile, extract macro definitions from it
+
+sub fetch_oci_macros {
+    my $file = shift;
+
+    # Read $file makefile, extract macro definitions from it
     # and store them in $MK, @MK and %MK.
 
     # Don't include the following definitions in the generated
     # makefile (note that %MK stills gets these values).
-    my @edit = qw(SHELL CC CFLAGS CCFLAGS OPTIMIZE ASFLAGS RCC LD LDFLAGS AR ECHO EXE OBJS);
+    my @edit = qw(
+		SHELL CC CFLAGS CCFLAGS OPTIMIZE ASFLAGS RCC LD LDFLAGS
+		AR ECHO EXE OBJS PERL
+	);
     my %edit; @edit{@edit} = ('$_ = ""') x @edit;
 
     $edit{COMPOBJS} = q{
 	# Firstly a Solaris specific edit:
-	if ($Config{osname} eq 'solaris') { # and $Config{gccversion}?
-	    # Change the COMPOBJS line. (Some files use LIBHOME not COMPOBJ)
-	    # old: $(COMPOBJ)/crti.o $(COMPOBJ)/crt1.o $(COMPOBJ)/__fstd.o
-	    # new: $(COMPOBJ)/__fstd.o
-	    s:\$\S+?/crt[1in]\.o\b::g;
-	}
+	del_crtobj() if $osname eq 'solaris';
 	
 	# Delete any object files in COMPOBJS that don't actually exist
 	my $of;
@@ -280,14 +311,22 @@ sub fetch_oci_macros {
     my $mkver = 0;
     my $linkwith = '';
     my $lastline = '';
-    my @lines = read_inc_file($procmk);
+    my @lines = read_inc_file($file);
     for(1; $_ = shift(@lines); $lastline = $_){
 	# Join split lines but retain backwack and newlines:
-	$_ .= shift(@lines) while(m/\\[\r\n]+$/);
+	$_ .= shift @lines while(m/\\[\r\n]+$/);
 	chomp;
-	push(@MK, '') if ($_ eq '' and $lastline ne '');
+	push @MK, '' if $_ eq '' and $lastline ne ''; # squeeze multiple blank lines
 	next unless $_;
-	last if m/^\w+\s*:[^=]/;	# gone too far, reached actual targets
+
+	if ($::opt_old) {
+	    last if m/^\w+\s*:[^=]/;	# gone too far, reached actual targets
+	}
+	else {
+	    next if m!^[-\w/+.\$()]+\s*:+[^=]*!; # skip targets
+	    next if m!^\t!;                      # skip target build rules
+	}
+	next if m/^\s*\.SUFFIXES/;
 
 	unless($MK{mkver}) {	# still need to get version number
 	    # This is tough since some versions of proc.mk split the
@@ -301,9 +340,12 @@ sub fetch_oci_macros {
 
 	# We always store values into %MK before checking %edit
 	# %edit can edit this in addition to $_ if needed.
-	$MK{$1} = $2 if m/^\s*(\w+)\s*=\s*([\s\S]*)/;
-
-	next if m/^\s*\.SUFFIXES/;
+	if ($::opt_old) {
+	    $MK{$1} = $2 if m/^\s*(\w+)\s*=\s*([\s\S]*)/;
+	}
+	else {
+	    $MK{$1}= $' if m/^\s*(\w+)\s*=\s*/;
+	}
 
 	if ($1 and exists $edit{$1}) {
 	    my $name = $1;
@@ -329,22 +371,23 @@ sub fetch_oci_macros {
 	$linkwith = '$(PROLDLIBS)';
     }
     unless ($linkwith){
-	die "ERROR parsing $procmk: Unable to determine what to link with.\n"
+	die "ERROR parsing $file: Unable to determine what to link with.\n"
 	."Please send me copies of these files (one per mail message):\n@mkfiles\n";
     }
     $MK = join("\n", @MK);
     return $linkwith;
 }
 
+
 sub read_inc_file {
     my $file = shift;
     my $fh;
     unless ($fh = new FileHandle "<$file") {
-		# Workaround more oracle bungling (Oracle 7.3.2/Solaris x86)
-		my $alt; ($alt = $file) =~ s/\.dk\.mk$/\.mk/;
-		$fh = new FileHandle "<$alt";
-		die "Unable to read $file: $!" unless $fh;
-	}
+	# Workaround more oracle bungling (Oracle 7.3.2/Solaris x86)
+	my $alt; ($alt = $file) =~ s/\.dk\.mk$/\.mk/;
+	$fh = new FileHandle "<$alt";
+	die "Unable to read $file: $!" unless $fh;
+    }
     print "Reading $file.\n";
     my @lines;
     push(@mkfiles, $file);
@@ -362,12 +405,13 @@ sub read_inc_file {
     return @lines;
 }
 
+
 sub expand_shellescape { 
     my($orig, $level) = @_;
     my $cmd = $orig;
     warn "\n$level * Evaluating \`$orig\`\n" if $::opt_v;
     # ensure we have no $(...) vars left - strip out undefined ones:
-    $cmd =~ s/\$\((\w+)\)/mkvar($1, 1, 0, $level+1)/ge;
+    $cmd =~ s/\$\((\w+)\)/mkvar("$1", 1, 0, $level+1)/ge;
     warn "\n$level * After reducing to \`$cmd\`\n" if $::opt_v and $cmd ne $orig;
     my $result = `$cmd`;
     warn "$level * Returned $result\n\n" if $::opt_v;
@@ -377,8 +421,8 @@ sub expand_mkvars {
     my($string, $strip, $backtick, $level) = @_;
     local($_) = $string;
     warn "$level Expanding $_\n" if $::opt_v;
-    s/\$\((\w+)\)/mkvar($1, $strip, $backtick, $level+1)/ge;
-    s/`(.*?[^\\])`/expand_shellescape($1, $level+1)/esg if $backtick;
+    s/\$\((\w+)\)/mkvar("$1", $strip, $backtick, $level+1)/ge; # can recurse
+    s/`(.*?[^\\])`/expand_shellescape("$1", $level+1)/esg if $backtick; # can recurse
     s/\s*\\\n\s*/ /g;	# merge continuations
     s/\s+/ /g;			# shrink whitespace
     warn "$level Expanded $string\n  to       $_\n\n" if $::opt_v and $_ ne $string;
@@ -390,7 +434,8 @@ sub mkvar {
     warn "$level Variable: $var\n" if $::opt_v;
     return '$(LIBHOME)' if $var eq 'LIBHOME' && !$strip; # gets noisy
     return $ENV{ORACLE_HOME} if $var eq 'ORACLE_HOME';
-    $MK{$var} ? expand_mkvars($MK{$var}, $strip, $backtick, $level+1) : $default;
+    return $default unless exists $MK{$var};
+    return expand_mkvars($MK{$var}, $strip, $backtick, $level+1); # can recurse
 }
 
 sub find_bin{
@@ -406,7 +451,10 @@ sub find_bin{
     sub const_cccmd {
 	my($self) = shift;
 	local($_) = $self->SUPER::const_cccmd(@_);
-	s/\s-O\d?\b/ -g/g if $::opt_g;
+	if ($::opt_g) {
+	    s/\s-O\d?\b//;	# delete optimise option
+	    s/\s-/ -g -/;	# add -g option
+	}
 	$_;
     }
 
